# Generated by Django 3.0 on 2020-09-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('friends_id', models.AutoField(primary_key=True, serialize=False)),
                ('friends_name', models.CharField(max_length=100, unique=True)),
                ('friends_record', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'friends_users',
                'managed': True,
            },
        ),
    ]
